name: Reusable CI Workflow

on:
  workflow_call:  # This makes it callable from other workflows

jobs:
  build_test_artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install dependencies with legacy peer deps
      run: npm install --legacy-peer-deps --force
    
    - name: Run tests
      run: npm test -- --json --outputFile=test-results.json || true
      continue-on-error: true
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: test-results.json
        retention-days: 1
