name: CI - Build and Validate React Components

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test_artifact:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies with peer conflict ignored
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # Run tests and generate results file
    - name: Run tests and create results file
      run: |
        if [ -f package.json ]; then
          npm test -- --json --outputFile=test-results.json || true
        else
          echo "No package.json found, skipping tests" > test-results.json
        fi
      continue-on-error: true

    # Upload test result artifact
    - name: Upload Test Results Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: test-results.json
        retention-days: 1
