name: CI Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Step 3: Install dependencies (ignore peer conflicts)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install --legacy-peer-deps
          else
            echo "No package.json found, skipping install"
          fi

      # Step 4: Run build (optional — only if your project needs build)
      - name: Build project
        run: |
          if [ -f package.json ]; then
            npm run build --if-present
          else
            echo "No build step found"
          fi

      # Step 5: Run tests
      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test --if-present
          else
            echo "No test script found"
          fi
