name: CI - Build and Validate React Components

on:
  workflow_dispatch:
  push:
    branches: [ master, auto/** ]
  pull_request:
    branches: [ master ]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/ci-reusable.yml
