name: UI Automation CI

on:
  workflow_dispatch:
  push:
    branches: [ "*" ] # Assuming your default branch is master
  pull_request:
    branches: [ "*" ]

jobs:
  build_test_artifact:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # --- Cache using npm now ---
        cache: 'npm'

    - name: Install dependencies
      # --- THIS IS THE FIXED LINE ---
      run: npm install --force # Use npm install --force

    # --- Update test command if needed (use npm if yarn test fails) ---
    - name: Run tests and create results file
      # Assuming 'yarn test' still works, otherwise use 'npm test -- --json --outputFile=test-results.json'
      run: npm test --json --outputFile=test-results.json
      continue-on-error: true

    - name: Upload Test Results Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: test-results.json
        retention-days: 1
