name: UI Automation CI

# This defines when the workflow runs
on:
  #  Run automatically when code is pushed to master or auto branches
  push:
    branches:
      - master
      - "auto/*"

  #  Run automatically for pull requests into master
  pull_request:
    branches:
      - master

  #  Allow manual dispatch from n8n or GitHub UI
  workflow_dispatch:

jobs:
  build_test_artifact:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # --- Step 1: Checkout repository ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Step 2: Setup Node.js environment ---
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # --- Step 3: Install dependencies (with fallback and safety) ---
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            echo "Installing with npm ci..."
            npm ci --legacy-peer-deps || npm install --force --legacy-peer-deps
          else
            echo "No lock file found, using npm install..."
            npm install --force --legacy-peer-deps
          fi

      # --- Step 4: Run tests ---
      # If you don't have tests yet, you can skip this or log a message
      - name: Run tests and create results file
        run: |
          if [ -f package.json ]; then
            echo "Running tests..."
            npm test -- --json --outputFile=test-results.json || echo "⚠️ Tests failed, continuing..."
          else
            echo "No package.json found, skipping tests."
          fi
        continue-on-error: true

      # --- Step 5: Upload test results as artifact ---
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-results.json
          retention-days: 1
