name: UI Automation CI

on:
  workflow_dispatch:
  push:
    branches: [ master ] # Assuming your default branch is master
  pull_request:
    branches: [ master ]

jobs:
  build_test_artifact:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      # --- THIS IS THE FIXED LINE ---
      run: yarn install --frozen-lockfile --force # Use --force flag

    - name: Run tests and create results file
      run: yarn test --json --outputFile=test-results.json
      continue-on-error: true

    - name: Upload Test Results Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: test-results.json
        retention-days: 1
